/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MULTIHERRAMIENTAS;

import java.sql.Connection;
//import java.sql.Date;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
        

/**
 *
 * @author Cachivan
 */
public class Catalogo_General extends javax.swing.JFrame {
    
    DefaultTableModel model;
    SimpleDateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
    Date fechaAct =new  Date();
    String hora = hourFormat.format(fechaAct);
    java.util.Date date = new Date();
    java.sql.Date fechaActual = new java.sql.Date(date.getTime());
    /**
     * Creates new form /
     */
    public void Habilitar(){
        //txtproducto.setEnabled(true);
        //txtprecio.setEnabled(true);
        Sstock.setEnabled(true);
        Spiezas.setEnabled(true);
    }
    
    public void Deshabilitar(){
        txtproducto.setEnabled(false);
        txtprecio.setEnabled(false);
        Sstock.setEnabled(false);
        Spiezas.setEnabled(false);
    }
    
    public void Limpiar(){
        txtproducto.setText("");
        txtprecio.setText("");
        Sstock.setValue(0);
        Spiezas.setValue(0);
    }
    
    public void Llenar(){
        String SQL="";
        try {
            ConexionDB con = new ConexionDB();
            Connection cnn = con.MySQLConnect();
            SQL="select * from PRODUCTOS";
            String[]titulos = {"ID_PRODUCTO","NOMBRE_PRODUCTO","NUMERO_PIEZAS","PRECIO_PRODUCTO","STOCK_MINIMO"};
            model = new DefaultTableModel(null, titulos);
            Statement st = cnn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            
            String[]fila=new String[5];
            while(rs.next()){
                fila[0] = rs.getString("ID_PRODUCTO");
                fila[1] = rs.getString("NOMBRE_PRODUCTO");
                fila[2] = rs.getString("NUMERO_PIEZAS");
                fila[3] = rs.getString("PRECIO_PRODUCTO");
                fila[4] = rs.getString("STOCK_MINIMO");
                
                model.addRow(fila);
            }
            JLista.setModel(model);
        } catch (Exception e){
    
            e.printStackTrace();
        }
       
        
            
        
        
        
    }
    
    public Catalogo_General() {
        
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        Llenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblNombreProducto = new javax.swing.JLabel();
        txtproducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Spiezas = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Sstock = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLista = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        BtnGuardar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuración de Catalogo");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LblNombreProducto.setText("Nombre Producto:");

        txtproducto.setEnabled(false);

        jLabel3.setText("Cantidad Piezas");

        Spiezas.setEnabled(false);

        jLabel4.setText("Precio Producto:");

        txtprecio.setEnabled(false);

        jLabel5.setText("Stock Minimo");

        Sstock.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblNombreProducto)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtprecio, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(txtproducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sstock))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Spiezas)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblNombreProducto)
                        .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Spiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JLista);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BtnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCancelar)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
        String SQL="";
        int fila=JLista.getSelectedRow();
        try{
               ConexionDB con = new ConexionDB();
               Connection cnn = con.MySQLConnect();    
               Statement st = cnn.createStatement();
               SQL="Update PRODUCTOS set NOMBRE_PRODUCTO=?,NUMERO_PIEZAS=?, PRECIO_PRODUCTO=?, STOCK_MINIMO=?, FECHA_MODIFICACION=?, HORA_MODIFICACION=?"+"where ID_PRODUCTO=?";
               String dao =(String)JLista.getValueAt(fila, 0);
               PreparedStatement ps = cnn.prepareCall(SQL);
               ps.setString(1, txtproducto.getText());
               ps.setInt(2, Integer.parseInt(Spiezas.getValue().toString()));
               ps.setDouble(3, Double.parseDouble(txtprecio.getText()));
               ps.setInt(4, Integer.parseInt(Sstock.getValue().toString()));
               ps.setDate(5, fechaActual);
               ps.setString(6, hora);
               ps.setString(7, dao);
               int n= ps.executeUpdate();
               if(n>0){
                    JOptionPane.showMessageDialog(null, "Datos guardados correctamente");
                }

            }catch (Exception e){
                        JOptionPane.showMessageDialog(null, "Error"+e.getMessage());            
            }
        
        Llenar();
        Limpiar();
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
        
        String SQL="";
        int val = Integer.parseInt(Sstock.getValue().toString());
        try {
            
            ConexionDB con = new ConexionDB();
            Connection cnn = con.MySQLConnect();
            SQL="insert into PRODUCTOS (NOMBRE_PRODUCTO, NUMERO_PIEZAS, PRECIO_PRODUCTO, STOCK_MINIMO, FECHA_MODIFICACION, HORA_MODIFICACION)"+"values (?,?,?,?,?,?)";
            PreparedStatement ps = cnn.prepareCall(SQL);
            ps.setString(1, txtproducto.getText());
            ps.setInt(2, Integer.parseInt(Spiezas.getValue().toString()));
            ps.setDouble(3, Double.parseDouble(txtprecio.getText()));
            ps.setInt(4, Integer.parseInt(Sstock.getValue().toString()));
            ps.setDate(5, fechaActual);
            ps.setString(6, hora);
            int n= ps.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(null, "Datos guardados correctamente");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error"+e.getMessage());
            
        }
        Llenar();
        Limpiar();
        
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void JListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JListaMouseClicked
        // TODO add your handling code here:
        String SQL="";
        if(evt.getButton()==1){
            int fila=JLista.getSelectedRow();
            try{
               ConexionDB con = new ConexionDB();
               Connection cnn = con.MySQLConnect();    
               Statement st = cnn.createStatement();
               Habilitar();
               SQL="select * from PRODUCTOS where ID_PRODUCTO="+JLista.getValueAt(fila, 0);
               ResultSet rs = st.executeQuery(SQL);
               rs.next();
               txtproducto.setText(rs.getString("NOMBRE_PRODUCTO"));
               txtprecio.setText(rs.getString("PRECIO_PRODUCTO"));
               Sstock.setValue(rs.getInt("STOCK_MINIMO"));
               Spiezas.setValue(rs.getInt("NUMERO_PIEZAS"));

            }catch (Exception ex){
            ex.printStackTrace();
            
            }
        }
    }//GEN-LAST:event_JListaMouseClicked

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
        String SQL="";
        int fila=JLista.getSelectedRow();
        try{
               ConexionDB con = new ConexionDB();
               Connection cnn = con.MySQLConnect();    
               Statement st = cnn.createStatement();
               SQL="delete from PRODUCTOS where ID_PRODUCTO="+JLista.getValueAt(fila, 0);
               int n = st.executeUpdate(SQL);
               if(n>0){
                JOptionPane.showMessageDialog(null, "Datos eleminados correctamente");
                }
               Llenar();
               Limpiar();

            }catch (Exception e){
                        JOptionPane.showMessageDialog(null, "Error"+e.getMessage());            
            }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        Deshabilitar();
        Limpiar();
        int fila=JLista.getSelectedRow();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo_General().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JTable JLista;
    private javax.swing.JLabel LblNombreProducto;
    private javax.swing.JSpinner Spiezas;
    private javax.swing.JSpinner Sstock;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtproducto;
    // End of variables declaration//GEN-END:variables
}
